### PR TITLE
new(security): create `SECURITY.md` file

### PR DESCRIPTION
**Pull request by DerekNonGeneric**
Refs: https://help.github.com/en/github/managing-security-vulnerabilities/adding-a-security-policy-to-your-repository

Signed-off-by: Derek Lewis <DerekNonGeneric@inf.is>

/cc @yuvilio @emmitrovic

### CODE REVIEW

**Review by DerekNonGeneric — COMMENTED** [review]
By any chance, would @lirantal or @ljharb have any advice on whether this security policy looks decent? We don't currently qualify for a Tidelift subscription, so that seems out of the question. The [Snyk Advisor](https://snyk.io/advisor/npm-package/@openinf/gh-file-importer#maintenance) or [Socket package profile](https://socket.dev/npm/package/@openinf/gh-file-importer) scores would improve if we deployed this along with our packages. 🤔

Any advice here would certainly be appreciated!

**Comment by ljharb** [comment]
Seems fine.

**Review by DerekNonGeneric — COMMENTED** [review]
Slight nit due to a repeated word, but double-checked and this seems to at least be satisfying the [guidance provided by the GitHub docs](https://help.github.com/en/github/managing-security-vulnerabilities/adding-a-security-policy-to-your-repository) on the matter, which should be alright for now.

**Comment by lirantal** [comment]
Looks good Derek.

Another reference you could take a look at [here](https://github.com/lirantal/npq/blob/master/SECURITY.md) is borrowed from the original recommendation of the Node.js Security WG where it also outline details about responsible disclosure, expectation for timeline, etc.

**Pull request merged**
